Classes = [
    {
        'cid': '{82706b3c-4660-489a-8944-b898d101b252}',
        'contract_ids': [
            '@mozilla.org/network/protocol/about;1?what=firedragon-%s' % page for page in [
                'newtab',
                'notes',
                'settings',
                'welcome',
            ]
        ],
        'esModule': 'resource://firedragon/modules/AboutRedirector.sys.mjs',
        'constructor': 'AboutRedirector',
    },
    {
        'cid': '{f70fda07-0fbd-43db-9374-dc0dedf1fcce}',
        'contract_ids': [
            '@firedragon/browser-startup;1',
        ],
        'esModule': 'resource://firedragon/modules/BrowserStartup.sys.mjs',
        'constructor': 'BrowserStartup',
    },
]
