printWidth: 120
tabWidth: 4
semi: true
singleQuote: true
vueIndentScriptAndStyle: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - '^node:'
  - '^(?!node:|@\/|\.|resource:)'
  - '^@\/'
  - '^\.'
  - '^resource:'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderParserPlugins:
  - typescript
  - decorators-legacy
overrides:
  - files:
      - '*.json'
      - '*.yaml'
      - '*.yml'
    options:
      tabWidth: 2
