packages:
  - '@types/gecko'
  - build
  - builtin-addons/notes
  - builtin-addons/qr-code
  - builtin-addons/settings
  - builtin-addons/startpage
  - builtin-addons/troubleshooting
  - builtin-addons/welcome
  - builtin-addons/workspaces
  - content
  - modules
  - shared

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  unrs-resolver: true

catalog:
  '@intlify/unplugin-vue-i18n': ^11.2.4
  '@quasar/extras': ^2.0.3
  '@quasar/vite-plugin': ^2.0.0
  '@unhead/vue': ^3.3.1
  '@vueuse/core': ^14.4.0
  '@vue/reactivity': ^3.5.41
  '@wxt-dev/browser': ^0.2.5
  '@wxt-dev/module-vue': ^1.0.3
  quasar: ^2.24.0
  sass-embedded: ^1.100.0
  tsdown: ^0.22.14
  typescript: ~6.0.3
  vite: ^8.2.1
  vite-plugin-vue-devtools: ^8.2.1
  vue: ^3.5.41
  vue-i18n: ^11.4.8
  vue-router: ^5.2.0
  wxt: ^0.21.4
