packages:
  - '@types/gecko'
  - build
  - builtin-addons/notes
  - builtin-addons/settings
  - builtin-addons/troubleshooting
  - builtin-addons/welcome
  - builtin-addons/workspaces
  - content
  - modules
  - newtab
  - shared

catalog:
  typescript: ~5.9.3
  vite: ^7.3.1
  wxt: ^0.20.18

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - spawn-sync
  - unrs-resolver

overrides:
  wxt>vite: 'catalog:'
