packages:
  - '@types/gecko'
  - build
  - builtin-addons/notes
  - builtin-addons/qr-code
  - builtin-addons/settings
  - builtin-addons/startpage
  - builtin-addons/troubleshooting
  - builtin-addons/welcome
  - builtin-addons/workspaces
  - content
  - modules
  - shared

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  sharp: true
  spawn-sync: true
  unrs-resolver: true
  workerd: true

catalog:
  tsdown: ^0.22.3
  typescript: ~6.0.3
  vite: ^8.1.3
  wxt: ^0.20.27
