#filter substitution
export const BuildConfig = {
#ifdef FIREDRAGON_SETTINGS
    FIREDRAGON_SETTINGS: '@FIREDRAGON_SETTINGS@',
#endif
#ifdef FIREDRAGON_THEME
    FIREDRAGON_THEME: '@FIREDRAGON_THEME@',
#endif
#ifdef FIREDRAGON_DEBUG
    FIREDRAGON_DEBUG: '@FIREDRAGON_DEBUG@',
#endif
#ifdef FIREDRAGON_UPDATE
    FIREDRAGON_UPDATE: '@FIREDRAGON_UPDATE@',
#endif
};
