eme.siteprompt2=Lejo %S të riprodhojë përmbajtje të kontrolluar nga DRM?
eme.block=Blloko
eme.block.accesskey=B
eme.allow2=Lejo
eme.allow2.accesskey=A
eme.remember2=Mbaje mend këtë vendim
webgl.siteprompt2=Lejo %S të krijojë një kontekst WebGL?
webgl.siteprompt2.warning=Kjo mund të përdoret për të identifikuar në mënyrë unike kompjuterin tuaj.
webgl.block=Blloko
webgl.block.accesskey=B
webgl.allow2=Lejo
webgl.allow2.accesskey=A
webgl.remember2=Mbaje mend këtë vendim
