Classes = [
    {
        'cid': '{f70fda07-0fbd-43db-9374-dc0dedf1fcce}',
        'contract_ids': [
            '@firedragon/config/config-loader;1',
        ],
        'esModule': 'resource://firedragon/modules/config/ConfigLoader.sys.mjs',
        'constructor': 'ConfigLoader',
    },
    {
        'cid': '{81669fe6-b9b7-4732-b9fc-f82a88adb8a2}',
        'contract_ids': [
            '@firedragon/config/config-version;1',
        ],
        'esModule': 'resource://firedragon/modules/config/ConfigVersion.sys.mjs',
        'constructor': 'ConfigVersion',
    },
    {
        'cid': '{82706b3c-4660-489a-8944-b898d101b252}',
        'contract_ids': [
            '@mozilla.org/network/protocol/about;1?what=firedragon-newtab',
            '@mozilla.org/network/protocol/about;1?what=firedragon-settings',
            '@mozilla.org/network/protocol/about;1?what=firedragon-welcome',
        ],
        'esModule': 'resource://firedragon/modules/AboutRedirector.sys.mjs',
        'constructor': 'AboutRedirector',
    },
    {
        'cid': '{38d37acf-8689-4d78-b6a4-ea9af97664a8}',
        'contract_ids': [
            '@firedragon/translation-feature-manager;1',
        ],
        'esModule': 'resource://firedragon/modules/TranslationFeatureManager.sys.mjs',
        'constructor': 'TranslationFeatureManager',
    },
]
