Classes = [
    {
        'cid': '{f70fda07-0fbd-43db-9374-dc0dedf1fcce}',
        'contract_ids': [
            '@firedragon/config/config-loader;1',
        ],
        'esModule': 'resource://firedragon/modules/config/ConfigLoader.sys.mjs',
        'constructor': 'ConfigLoader',
    },
    {
        'cid': '{81669fe6-b9b7-4732-b9fc-f82a88adb8a2}',
        'contract_ids': [
            '@firedragon/config/config-version;1',
        ],
        'esModule': 'resource://firedragon/modules/config/ConfigVersion.sys.mjs',
        'constructor': 'ConfigVersion',
    },
]
