export enum ShortcutModifier {
    ACCEL = 'accel',
    ALT = 'alt',
    META = 'meta',
    SHIFT = 'shift',
}
export enum ShortcutKey {
    PK_0 = '0',
    PK_1 = '1',
    PK_2 = '2',
    PK_3 = '3',
    PK_4 = '4',
    PK_5 = '5',
    PK_6 = '6',
    PK_7 = '7',
    PK_8 = '8',
    PK_9 = '9',
    PK_A = 'A',
    PK_B = 'B',
    PK_C = 'C',
    PK_D = 'D',
    PK_E = 'E',
    PK_F = 'F',
    PK_G = 'G',
    PK_H = 'H',
    PK_I = 'I',
    PK_J = 'J',
    PK_K = 'K',
    PK_L = 'L',
    PK_M = 'M',
    PK_N = 'N',
    PK_O = 'O',
    PK_P = 'P',
    PK_Q = 'Q',
    PK_R = 'R',
    PK_S = 'S',
    PK_T = 'T',
    PK_U = 'U',
    PK_V = 'V',
    PK_W = 'W',
    PK_X = 'X',
    PK_Y = 'Y',
    PK_Z = 'Z',
    PK_BACK_QUOTE = '`',
    PK_BACK_SLASH = '\\',
    PK_CLOSE_BRACKET = ']',
    PK_COMMA = ',',
    PK_EQUALS = '=',
    PK_MINUS = '-',
    PK_OPEN_BRACKET = '[',
    PK_PERIOD = '.',
    PK_PLUS = '+',
    PK_QUOTE = "'",
    PK_SEMICOLON = ';',
    PK_SLASH = '/',
    PK_STAR = '*',
    VK_F1 = 'VK_F1',
    VK_F2 = 'VK_F2',
    VK_F3 = 'VK_F3',
    VK_F4 = 'VK_F4',
    VK_F5 = 'VK_F5',
    VK_F6 = 'VK_F6',
    VK_F7 = 'VK_F7',
    VK_F8 = 'VK_F8',
    VK_F9 = 'VK_F9',
    VK_F10 = 'VK_F10',
    VK_F11 = 'VK_F11',
    VK_F12 = 'VK_F12',
    VK_F13 = 'VK_F13',
    VK_F14 = 'VK_F14',
    VK_F15 = 'VK_F15',
    VK_F16 = 'VK_F16',
    VK_F17 = 'VK_F17',
    VK_F18 = 'VK_F18',
    VK_F19 = 'VK_F19',
    VK_F20 = 'VK_F20',
    VK_F21 = 'VK_F21',
    VK_F22 = 'VK_F22',
    VK_F23 = 'VK_F23',
    VK_F24 = 'VK_F24',
    VK_RETURN = 'VK_RETURN',
}

export enum ShortcutCommand {
    ADD_BOOKMARK_AS = 'Browser:AddBookmarkAs',
    BACK = 'Browser:Back',
    BOOKMARK_ALL_TABS = 'Browser:BookmarkAllTabs',
    CLOSE_TAB = 'cmd_close',
    CLOSE_WINDOW = 'cmd_closeWindow',
    FIND = 'cmd_find',
    FIND_AGAIN = 'cmd_findAgain',
    FIND_PREVIOUS = 'cmd_findPrevious',
    FIND_SELECTION = 'cmd_findSelection',
    FORWARD = 'Browser:Forward',
    FULL_ZOOM_ENLARGE = 'cmd_fullZoomEnlarge',
    FULL_ZOOM_REDUCE = 'cmd_fullZoomReduce',
    FULL_ZOOM_RESET = 'cmd_fullZoomReset',
    FULL_ZOOM_TOGGLE = 'cmd_fullZoomToggle',
    FULLSCREEN = 'View:FullScreen',
    NEW_NAVIGATOR = 'cmd_newNavigator',
    NEW_NAVIGATOR_TAB = 'cmd_newNavigatorTab',
    NEXT_TAB = 'Browser:NextTab',
    OPEN_FILE = 'Browser:OpenFile',
    PAGE_SOURCE = 'View:PageSource',
    PREV_TAB = 'Browser:PrevTab',
    QUIT = 'cmd_quitApplication',
    READER_VIEW = 'View:ReaderView',
    RELOAD = 'Browser:Reload',
    SAVE_PAGE = 'Browser:SavePage',
    SEARCH_BOOKMARKS = 'Browser:SearchBookmarks',
    SEARCH_HISTORY = 'History:SearchHistory',
    STOP = 'Browser:Stop',
    TRANSLATE = 'cmd_translate',
    UNDO_CLOSE_TAB = 'History:UndoCloseTab',
    UNDO_CLOSE_WINDOW = 'History:UndoCloseWindow',
}

export interface Shortcut {
    id: string;
    modifiers: ShortcutModifier[];
    key: ShortcutKey;
    command: ShortcutCommand;
}
